# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# auto exec custom script at startup for refreshing mirrorlist
exec-once = ~/.config/hypr/custom/scripts/refresh-mirrors.sh

# Force Ferdium to use Wayland backend and launch on start
# exec-once = ferdium --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime

# Launch the firewall applet on startup
# exec-once = firewall-applet

# auto stop triggerhappy: configs brightness keybinds for sddm. But dont want to mess with hyprland
# Stop triggerhappy on login to avoid double brightness triggers
exec-once = sudo systemctl stop triggerhappy
