# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# vscode save unsaved file alert promptbox rules
# windowrule = match:class ^(code)$. match:float 1, stay_focused on
# windowrule = match:class ^(code)$. match:float 1, dim_around on

# Kde calk calculator window rules
# Kalk (KDE Calculator)
# windowrulev2 = workspace special:kalk silent, class:^(org.kde.kalk)$

windowrule = match:class ^(org.kde.kalk)$, float on
windowrule = match:class ^(org.kde.kalk)$, size 400 550
windowrule = match:class ^(org.kde.kalk)$, max_size 400 650
windowrule = match:class ^(org.kde.kalk)$, move 1519 1
# windowrule = match:class ^(org.kde.kalk)$, pin on
windowrule = match:class ^(org.kde.kalk)$, keep_aspect_ratio on
windowrule = match:class ^(org.kde.kalk)$, animation slide right

# windowrule = match:class ^(org.kde.kalk)$, stay_focused on
# layerrule = match:class ^(org.kde.kalk)$, blur on
# windowrule = match:class ^(org.kde.kalk)$, border_color rgba(b3ff1aee)



# Force Kalk into the background scratchpad and fix its size/position
# windowrulev2 = float, class:^(org.kde.kalk)$
# windowrulev2 = size 400 650, class:^(org.kde.kalk)$
# windowrulev2 = move 1519 1, class:^(org.kde.kalk)$

# Kalk - Special Workspace (Scratchpad)
# windowrulev2 = float, class:^(org.kde.kalk)$
# windowrulev2 = size 400 550, class:^(org.kde.kalk)$
# windowrulev2 = move 1508 1, class:^(org.kde.kalk)$
# windowrulev2 = animation slide right, class:^(org.kde.kalk)$
